      INTEGER DUM(40),IRADCO(6)
      CHARACTER*8 ARADN(6),ARADCH(6)
      CHARACTER*1 COEFCH(6),LPARA,RPARA,BLANK
      REAL*8 Q(176),X(176)
      CHARACTER*60 NAME
      CHARACTER*11 FILENAMEEND

C*****
C OPEN THE FILE CONTAINING THE CROSS SECTIONS
C AND THE CROSS SECTION CATALOG FILE
C*****
      FILENAMEEND='_LORES1.DAT'
      OPEN(30,FILE='crossdisk2-use.inp-moses')
      OPEN(20,FILE='crossdisk-catalog.dat')

C*****
C READ INFO FROM CROSSDISK-USE FILE
C IRADCO = STOICH. COEFFICIENTS
C ARADN = REACTANT AND PRODUCT SPECIES NAMES
C IR1,IR2 = BEGINNING AND ENDING WAVELENTH INDICES
C TTC = TEMPERATURE FOR THE CROSS SECTIONS
C X(J) = THE WAVELENGTH
C Q(J) = THE CROSS SECTION VALUE
C*****
      DO 440 I = 1,1000
410      READ(30,411,END=440) (IRADCO(J),ARADN(J),ARADCH(J),J=1,6),
     1        IR1,IR2,NUM,TTC,(DUM(J),J=1,5)
411      FORMAT(/6(I1,A8,A1),2(I3,1X),I3,1X,F5.1,1X,10A1)
         DO 413 JJ=1,176,7
            JX=MIN(JJ+6,176)
            READ(30,412) (X(j),Q(J),J=JJ,JX)
412         FORMAT(5X,7(1X,0PF6.1,1PE10.3))
413      CONTINUE

C*****
C CREATE A NAME FOR THE OUTPUT FILE BASED ON THE NAMES OF THE
C REACANT AND PRODUCT SPECIES, REMOVE ( AND ) FROM THE NAME, IF
C PRESENT
C*****
         LPARA='('
         RPARA=')'
         BLANK=' '
         NAME=' '

      DO J = 1,6
         IF(IRADCO(J).NE.0) THEN
            WRITE(COEFCH(J),420) IRADCO(J)
            NAME=TRIM(NAME)//TRIM(COEFCH(J))
         ENDIF
         IF(SCAN(ARADN(J),LPARA).NE.0) THEN
            NAME=TRIM(NAME)//TRIM(ARADN(J)(1:INDEX(ARADN(J),LPARA)-1))
            NAME=TRIM(NAME)//'_'
            IF(SCAN(ARADN(J),RPARA).NE.0) THEN
               NAME=TRIM(NAME)//TRIM(ARADN(J)
     >              (INDEX(ARADN(J),LPARA)+1:INDEX(ARADN(J),RPARA)-1))
               NAME=TRIM(NAME)//'_'
               NAME=TRIM(NAME)//TRIM(ARADN(J)
     >              (INDEX(ARADN(J),RPARA)+1:8))

            ENDIF
         ELSE IF(SCAN(TRIM(ARADN(J)),BLANK).NE.0) THEN
            NAME=TRIM(NAME)//
     >           TRIM(ARADN(J)(1:INDEX(TRIM(ARADN(J)),BLANK)-1))
            NAME=TRIM(NAME)//'_'
            NAME=TRIM(NAME)//TRIM(ARADN(J)
     >           (INDEX(TRIM(ARADN(J)),BLANK)+1:8))
         ELSE
            NAME=TRIM(NAME)//ARADN(J)
         ENDIF
         NAME=TRIM(NAME)//ARADCH(J)
      ENDDO

      NAME='CROSS_'//NAME
      NAME=TRIM(NAME)//FILENAMEEND

C*****
C OPEN THE FILE TO WHICH THE CROSS SECTION DATA WILL BE WRITTEN
C*****
      OPEN(40,FILE=NAME)

C*****
C WRITE THE REACTION FOLLOWED BY THE TEMPERATURE, BEGINNING AND ENDING WAVELENGTH
C INDICIES, WAVELENTGH, AND CROSS SECTION VALUES TO THE OUTPUT FILE CREATED
C ABOVE
C*****
      DO J = 1,6
         IF(IRADCO(J).NE.0) THEN
            WRITE(COEFCH(J),420) IRADCO(J)
420         FORMAT(I1)
         ELSE
            WRITE(COEFCH(J),422) ' '
422         FORMAT(A1)
         ENDIF
      ENDDO

      WRITE(40,421) (COEFCH(J),ARADN(J),ARADCH(J),J=1,6)
421   FORMAT(6(A1,A8,A1))

      WRITE(40,416) 1,TTC
416   FORMAT(I1,1X,F5.1)
      WRITE(40,417) IR1,IR2
417   FORMAT(I3,1X,I3)

      DO J=IR1,IR2
         WRITE(40,414) X(J),Q(J)
 414     FORMAT((0PF6.1,1X,1PE10.3))
      ENDDO

C*****
C WRITE THE REACTION AND FILE NAME TO THE CATALOG FILE
C*****
      WRITE(20,419) (COEFCH(J),ARADN(J),ARADCH(J),J=1,6),NAME
419   FORMAT(6(A1,A8,A1),1X,A48)

      WRITE(0,*) ' wrote cross sections to ' , TRIM(NAME)

      CLOSE(40)

440   CONTINUE

      CLOSE(20)
      CLOSE(30)

      STOP
      END
