#ifndef SAT_LINDAL92_HPP
#define SAT_LINDAL92_HPP

/** @file sat_lindal92.hpp"
  *
  * This file is automatically generated by make_sat_lindal92.py
  *
  * @author Cheng Li
  */
namespace Saturn {
  extern int const lindal92_num;
  extern double const lindal92_T[];
  extern double const lindal92_P[];
}

#endif
