#ifndef SRC_ASTRO_SATURN_SAT_LINDAL92_HPP_
#define SRC_ASTRO_SATURN_SAT_LINDAL92_HPP_

/** @file sat_lindal92.hpp"
 *
 * This file is automatically generated by make_sat_lindal92.py
 *
 * @author Cheng Li
 */
namespace Saturn {
extern int const lindal92_num;
extern double const lindal92_T[];
extern double const lindal92_P[];
}  // namespace Saturn

#endif  // SRC_ASTRO_SATURN_SAT_LINDAL92_HPP_
