# define default parameters

list(APPEND CMAKE_PREFIX_PATH "/usr/include/mpich-x84_64" "/usr/lib64/mpich/")

# dirty
set_if_empty(NBLOCKS 0)

if(NOT AFFINE OR NOT DEFINED AFFINE)
  set(AFFINE_OPTION "NOT_AFFINE")
else()
  set(AFFINE_OPTION "AFFINE")
  set(COORDINATE_SYSTEM "affine_coordinate")
endif()

if(NOT CUBED_SPHERE OR NOT DEFINED CUBED_SPHERE)
  set(CUBED_SPHERE_OPTION "NOT_CUBED_SPHERE")
else()
  set(CUBED_SPHERE_OPTION "CUBED_SPHERE")
  set(COORDINATE_SYSTEM "gnomonic_equiangle")
endif()

if(NOT NETCDF OR NOT DEFINED NETCDF)
  set(NETCDF_OPTION "NO_NETCDFOUTPUT")
else()
  set(NETCDF_OPTION "NETCDFOUTPUT")
  find_package(NetCDF REQUIRED)
endif()

if(NOT PNETCDF OR NOT DEFINED PNETCDF)
  set(PNETCDF_OPTION "NO_PNETCDFOUTPUT")
else()
  set(PNETCDF_OPTION "PNETCDFOUTPUT")
  find_package(PNetCDF REQUIRED)
endif()

if(NOT FITS OR NOT DEFINED FITS)
  set(FITS_OPTION "NO_FITSOUTPUT")
else()
  set(FITS_OPTION "FITSOUTPUT")
  find_package(cfitsio REQUIRED)
endif()

if(NOT HYDROSTATIC OR NOT DEFINED HYDROSTATIC)
  set(HYDROSTATIC_OPTION "NOT_HYDROSTATIC")
else()
  set(HYDROSTATIC_OPTION "HYDROSTATIC")
endif()

if(NOT MPI OR NOT DEFINED MPI)
  set(MPI_OPTION "NOT_MPI_PARALLEL")
else()
  set(MPI_OPTION "MPI_PARALLEL")
  find_package(
    MPI
    COMPONENTS C
    REQUIRED)
endif()

if(NOT NBLOCKS OR NOT DEFINED NBLOCKS)
  set(USE_NBLOCKS "NOT_USE_NBLOCKS")
else()
  set(USE_NBLOCKS "USE_NBLOCKS")
endif()
