#ifndef SRC_ASTRO_JUPITER_JUP_FLETCHER16_CIRS_HPP_
#define SRC_ASTRO_JUPITER_JUP_FLETCHER16_CIRS_HPP_

/** @file jup_fletcher16_cirs.hpp"
 *
 * This file is automatically generated by make_jup_fletcher16_cirs.py
 *
 * @author Cheng Li
 */

namespace Jupiter {
extern size_t const fletcher16_cirs_npres;
extern size_t const fletcher16_cirs_nglat;
extern double const fletcher16_cirs_glat[];
extern double const fletcher16_cirs_pres[];
extern double const fletcher16_cirs_temp[][120];
double get_temp_fletcher16_cirs(double glat, double pbar);
}  // namespace Jupiter

#endif  // SRC_ASTRO_JUPITER_JUP_FLETCHER16_CIRS_HPP_
