#ifndef JUP_FLETCHER16_CIRS_HPP
#define JUP_FLETCHER16_CIRS_HPP

/** @file jup_fletcher16_cirs.hpp"
  *
  * This file is automatically generated by make_jup_fletcher16_cirs.py
  *
  * @author Cheng Li
  */
namespace Jupiter {
  extern int const fletcher16_cirs_npres;
  extern int const fletcher16_cirs_nglat;
  extern double const fletcher16_cirs_glat[];
  extern double const fletcher16_cirs_pres[];
  extern double const fletcher16_cirs_temp[][120];
  double get_temp_fletcher16_cirs(double glat, double pbar);
}

#endif
